/**
 * Seed NEV Database with Test Data
 * Usage: npx ts-node scripts/seed-nev-test-data.ts
 */

async function seedTestData() {
  const data = {
    brands: [
      {
        name: 'BYD',
        nameTh: 'บีวายดี',
        slug: 'byd',
        logoUrl: null,
        country: 'China',
        website: 'https://www.byd.com',
      },
      {
        name: 'Tesla',
        nameTh: 'เทสลา',
        slug: 'tesla',
        logoUrl: null,
        country: 'USA',
        website: 'https://www.tesla.com',
      },
      {
        name: 'MG',
        nameTh: 'เอ็มจี',
        slug: 'mg',
        logoUrl: null,
        country: 'UK/China',
        website: 'https://www.mg.co.th',
      },
    ],
    models: [
      {
        brandSlug: 'byd',
        name: 'Dolphin',
        nameTh: 'ดอลฟิน',
        slug: 'byd-dolphin',
        fullName: 'BYD Dolphin',
        year: 2026,
        bodyType: 'Hatchback',
        segment: 'B',
        seats: 5,
        powertrain: 'BEV',
        assembly: 'CKD',
        madeIn: 'Thailand',
        imageUrl: null,
        overview: 'รถยนต์ไฟฟ้าขนาดกะทัดรัด เหมาะสำหรับการขับขี่ในเมือง',
        highlights: [
          'แบตเตอรี่ Blade Battery ปลอดภัยสูง',
          'ระยะทางไกลสุด 427 กม.',
          'ดีไซน์สไตล์ Ocean Aesthetics',
        ],
        isNewModel: true,
        launchDate: '2026-01-15',
      },
      {
        brandSlug: 'tesla',
        name: 'Model 3',
        nameTh: 'โมเดล 3',
        slug: 'tesla-model-3',
        fullName: 'Tesla Model 3',
        year: 2026,
        bodyType: 'Sedan',
        segment: 'D',
        seats: 5,
        powertrain: 'BEV',
        assembly: 'CBU',
        madeIn: 'China',
        imageUrl: null,
        overview: 'รถยนต์ไฟฟ้าสมรรถนะสูง ครบครันด้วยเทคโนโลยี Autopilot',
        highlights: [
          'ระบบ Autopilot ขั้นสูง',
          'เร่ง 0-100 ภายใน 3.1 วินาที (Performance)',
          'ระยะทางไกลสุด 629 กม.',
        ],
        isNewModel: false,
        launchDate: null,
      },
      {
        brandSlug: 'mg',
        name: 'MG4 Electric',
        nameTh: 'เอ็มจี4 อิเล็กทริก',
        slug: 'mg-mg4-electric',
        fullName: 'MG MG4 Electric',
        year: 2026,
        bodyType: 'Hatchback',
        segment: 'C',
        seats: 5,
        powertrain: 'BEV',
        assembly: 'CBU',
        madeIn: 'China',
        imageUrl: null,
        overview: 'รถยนต์ไฟฟ้าสไตล์สปอร์ตแฮทช์แบ็ก พร้อมสมรรถนะที่ตอบโจทย์',
        highlights: [
          'ขุมพลัง 170 kW เร่งแรง',
          'แบตเตอรี่ 64 kWh',
          'ราคาเริ่มต้นคุ้มค่า',
        ],
        isNewModel: false,
        launchDate: null,
      },
    ],
    variants: [
      // BYD Dolphin
      {
        modelSlug: 'byd-dolphin',
        name: 'Dynamic',
        fullName: 'BYD Dolphin Dynamic',
        slug: 'byd-dolphin-dynamic',
        priceBaht: 829000,
        priceNote: null,
        batteryKwh: 44.9,
        rangeKm: 340,
        rangeStandard: 'CLTC',
        motorCount: 1,
        motorKw: 70,
        motorHp: 95,
        torqueNm: 180,
        topSpeedKmh: 150,
        accel0100: null,
        drivetrain: 'FWD',
        dcChargeKw: 60,
        dcChargeMin: 29,
        acChargeKw: 7,
        chargePort: 'CCS2',
        lengthMm: 4290,
        widthMm: 1770,
        heightMm: 1570,
        wheelbaseMm: 2700,
        groundClearanceMm: null,
        curbWeightKg: 1405,
        grossWeightKg: null,
        trunkLitres: 345,
        warrantyVehicle: '5 ปี / 150,000 กม.',
        warrantyBattery: '8 ปี / 160,000 กม.',
        features: JSON.stringify({
          safety: ['ABS', 'ESC', '6 ถุงลม'],
          adas: ['FCW', 'AEB', 'LDW'],
          comfort: ['ปรับอากาศอัตโนมัติ', 'เบาะหนัง'],
        }),
        hasV2l: true,
        v2lKw: 3.3,
        hasV2g: false,
        isBestSeller: true,
        dataSource: 'manual',
      },
      {
        modelSlug: 'byd-dolphin',
        name: 'Extended Range',
        fullName: 'BYD Dolphin Extended Range',
        slug: 'byd-dolphin-extended',
        priceBaht: 979000,
        priceNote: null,
        batteryKwh: 60.48,
        rangeKm: 427,
        rangeStandard: 'CLTC',
        motorCount: 1,
        motorKw: 150,
        motorHp: 204,
        torqueNm: 310,
        topSpeedKmh: 160,
        accel0100: 7.5,
        drivetrain: 'FWD',
        dcChargeKw: 60,
        dcChargeMin: 38,
        acChargeKw: 7,
        chargePort: 'CCS2',
        lengthMm: 4290,
        widthMm: 1770,
        heightMm: 1570,
        wheelbaseMm: 2700,
        groundClearanceMm: null,
        curbWeightKg: 1505,
        grossWeightKg: null,
        trunkLitres: 345,
        warrantyVehicle: '5 ปี / 150,000 กม.',
        warrantyBattery: '8 ปี / 160,000 กม.',
        features: JSON.stringify({
          safety: ['ABS', 'ESC', '6 ถุงลม'],
          adas: ['FCW', 'AEB', 'LDW', 'ACC'],
          comfort: ['ปรับอากาศอัตโนมัติ', 'เบาะหนัง', 'พวงมาลัยหนัง'],
        }),
        hasV2l: true,
        v2lKw: 3.3,
        hasV2g: false,
        isBestSeller: false,
        dataSource: 'manual',
      },
      // Tesla Model 3
      {
        modelSlug: 'tesla-model-3',
        name: 'Long Range',
        fullName: 'Tesla Model 3 Long Range',
        slug: 'tesla-model-3-long-range',
        priceBaht: 1899000,
        priceNote: null,
        batteryKwh: 78.1,
        rangeKm: 629,
        rangeStandard: 'WLTP',
        motorCount: 2,
        motorKw: 366,
        motorHp: 496,
        torqueNm: 493,
        topSpeedKmh: 233,
        accel0100: 4.4,
        drivetrain: 'AWD',
        dcChargeKw: 250,
        dcChargeMin: 27,
        acChargeKw: 11,
        chargePort: 'CCS2',
        lengthMm: 4720,
        widthMm: 1933,
        heightMm: 1441,
        wheelbaseMm: 2875,
        groundClearanceMm: null,
        curbWeightKg: 1844,
        grossWeightKg: null,
        trunkLitres: 561,
        warrantyVehicle: '4 ปี / 80,000 กม.',
        warrantyBattery: '8 ปี / 192,000 กม.',
        features: JSON.stringify({
          safety: ['8 ถุงลม', 'ABS', 'ESC'],
          adas: ['Autopilot', 'Auto Lane Change', 'Auto Park'],
          comfort: ['Glass Roof', 'Premium Audio', 'Heated Seats'],
        }),
        hasV2l: false,
        v2lKw: null,
        hasV2g: false,
        isBestSeller: true,
        dataSource: 'manual',
      },
      // MG MG4 Electric
      {
        modelSlug: 'mg-mg4-electric',
        name: 'X-Power',
        fullName: 'MG MG4 Electric X-Power',
        slug: 'mg-mg4-electric-xpower',
        priceBaht: 1390000,
        priceNote: null,
        batteryKwh: 64,
        rangeKm: 450,
        rangeStandard: 'WLTP',
        motorCount: 2,
        motorKw: 170,
        motorHp: 231,
        torqueNm: 250,
        topSpeedKmh: 200,
        accel0100: 7.7,
        drivetrain: 'AWD',
        dcChargeKw: 130,
        dcChargeMin: 35,
        acChargeKw: 11,
        chargePort: 'CCS2',
        lengthMm: 4287,
        widthMm: 1836,
        heightMm: 1504,
        wheelbaseMm: 2705,
        groundClearanceMm: null,
        curbWeightKg: 1685,
        grossWeightKg: null,
        trunkLitres: 363,
        warrantyVehicle: '5 ปี / 100,000 กม.',
        warrantyBattery: '7 ปี / 150,000 กม.',
        features: JSON.stringify({
          safety: ['6 ถุงลม', 'ABS', 'ESC'],
          adas: ['ACC', 'LDW', 'FCW', 'AEB'],
          comfort: ['17" Alloy Wheels', 'Panoramic Sunroof'],
        }),
        hasV2l: true,
        v2lKw: 3,
        hasV2g: false,
        isBestSeller: false,
        dataSource: 'manual',
      },
    ],
  };

  console.log('🚀 Seeding test data to /api/nev/import...\n');
  
  try {
    const response = await fetch('http://localhost:3002/api/nev/import', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    });

    const result = await response.json();
    
    if (response.ok) {
      console.log('✅ Import successful!');
      console.log('\n📊 Results:');
      console.log(`   Brands: ${result.imported.brands}`);
      console.log(`   Models: ${result.imported.models}`);
      console.log(`   Variants: ${result.imported.variants}`);
    } else {
      console.error('❌ Import failed:', result);
    }
  } catch (error) {
    console.error('❌ Error:', error);
  }
}

seedTestData();
